# © 2019 Numigi
# License LGPL-3.0 or later (http://www.gnu.org/licenses/lgpl).

{
    "name": "Main Module",
    "version": "14.0.1.0.0",
    "author": "Numigi",
    "maintainer": "Numigi",
    "website": "https://www.numigi.com",
    "license": "LGPL-3",
    "category": "Other",
    "summary": "Install all addons required for testing.",
    "depends": [
        "crm_brand",
        "delivery_carrier_fixed_over",
        "event_sale_order_status",
        "payment_auto_confirm_sale_order",
        "sale_default_term_on_company",
        "sale_delivery_completion",
        "sale_delivery_completion_rental",
        "sale_dynamic_price",
        "sale_invoice_email_warning",
        "sale_invoice_group_by_order",
        "sale_kit",
        "sale_minimum_margin",
        "sale_order_available_qty_popover",
        "sale_order_available_qty_popover_rental",
        "sale_order_line_readonly_conditions",
        "sale_order_margin_percent",
        "sale_order_weight",
        "sale_persistent_product_warning",
        "sale_privilege_level",
        "sale_privilege_level_delivery",
        "sale_privilege_level_payment",
        "sale_privilege_level_pricelist",
        "sale_privilege_level_rental_pricelist",
        "sale_privilege_level_website",
        "sale_rental",
        "sale_rental_app",
        "sale_rental_portal",
        "sale_rental_pricelist",
        "sale_rental_status",
        "sale_warranty",
        "sale_warranty_extension",
        "sale_warranty_lead_on_expiry",
        "sale_xmlrpc_compatible",
        "website_payment_message_enhanced",
    ],
    "installable": True,
}
