# © 2023 Numigi
# License LGPL-3.0 or later (http://www.gnu.org/licenses/lgpl).

{
    "name": "Main Module",
    "version": "14.0.1.0.0",
    "author": "Numigi",
    "maintainer": "Numigi",
    "website": "https://www.numigi.com",
    "license": "LGPL-3",
    "category": "Other",
    "summary": "Install all addons required for testing.",
    "depends": [
        "crm_assign_by_area",
        "crm_assign_in_house",
        "crm_brand",
        "crm_kanban_prorated_revenue",
        "crm_lead_product",
        "crm_team_by_industry",
        "delivery_carrier_fixed_over",
        "event_sale_order_status",
        "partner_sale_target",
        "partner_sale_target_change_parent_binding",
        "payment_auto_confirm_sale_order",
        "product_configurator_sale_ext",
        "product_pack_ext",
        "sale_commitment_date_update",
        "sale_commitment_date_update_mrp",
        "sale_coupon_apply_on_domain",
        "sale_default_analytic_tag",
        "sale_default_term_on_company",
        "sale_delivery_completion",
        "sale_delivery_completion_rental",
        "sale_display_qty_widget_secondary_unit",
        "sale_double_validation",
        "sale_double_validation_extend",
        "sale_dynamic_price",
        "sale_intercompany_service",
        "sale_invoice_email_warning",
        "sale_invoice_group_by_order",
        "sale_invoice_no_follow",
        "sale_kit",
        "sale_minimum_margin",
        "sale_order_default_taxes",
        "sale_order_groupby_parent_affiliate",
        "sale_order_line_checkbox",
        "sale_order_line_margin_amount",
        "sale_order_line_readonly_conditions",
        "sale_order_margin_percent",
        "sale_order_partner_restrict_affiliates",
        "sale_order_portal_hide_invoices",
        "sale_order_type_email_template",
        "sale_order_url_tracking",
        "sale_order_weight",
        "sale_partner_authorized_company",
        "sale_persistent_product_warning",
        "sale_privilege_level",
        "sale_privilege_level_delivery",
        "sale_privilege_level_payment",
        "sale_privilege_level_pricelist",
        "sale_privilege_level_rental_pricelist",
        "sale_privilege_level_website",
        "sale_product_configurator_img_width",
        "sale_product_pack_configurator_binding",
        "sale_product_pack_ext",
        "sale_product_pack_modifiable",
        "sale_project_description",
        "sale_project_milestone",
        "sale_qweb_report_website_desc",
        "sale_rental",
        "sale_rental_app",
        "sale_rental_order_swap_variant",
        "sale_rental_portal",
        "sale_rental_pricelist",
        "sale_rental_status",
        "sale_report_partner",
        "sale_stock_availability_popover",
        "sale_stock_move_no_merge",
        "sale_subscription_extended",
        "sale_target_margin",
        "sale_warranty",
        "sale_warranty_groupby_parent_affiliate",
        "sale_whole_order_invoiced",
        "sale_xmlrpc_compatible",
        "sales_team_account_journal",
        "web_view_google_map_itinerary",
        "website_payment_message_enhanced",
        "website_sale_request_price",
        "website_sale_request_price_wishlist",
        "website_stock_availability_enhanced",
    ],
    "installable": True,
}
