# © 2019 Numigi
# License LGPL-3.0 or later (http://www.gnu.org/licenses/lgpl).

{
    "name": "Main Module",
    "version": "1.0.0",
    "author": "Numigi",
    "maintainer": "Numigi",
    "website": "https://www.numigi.com",
    "license": "LGPL-3",
    "category": "Other",
    "summary": "Install all addons required for testing.",
    "depends": [
        "crm_brand",
        "sale_default_term_on_company",
        "sale_delivery_completion",
        "sale_dynamic_price",
        "sale_kit",
        "sale_minimum_margin",
        "sale_order_available_qty_popover",
        "sale_order_line_readonly_conditions",
        "sale_order_margin_percent",
        "sale_order_url_tracking",
        "sale_order_weight",
        "sale_partner_authorized_company",
        "sale_persistent_product_warning",
        "sale_privilege_level",
        "sale_privilege_level_delivery",
        "sale_privilege_level_payment",
        "sale_privilege_level_pricelist",
        "sale_privilege_level_website",
        "sale_rental",
        "sale_rental_order_swap_variant",
        "sale_stock_move_no_merge",
        "sale_warranty",
        "sale_warranty_extension",
        "sale_warranty_lead_on_expiry",
        "sale_whole_order_invoiced",
        "web_view_google_map_itinerary",
        "website_sale_request_price",
        "website_sale_request_price_wishlist",
        "website_stock_availability_enhanced",
    ],
    "installable": True,
}
